// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muxddlqdgatgdvhmylix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11eGRkbHFkZ2F0Z2R2aG15bGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDQ3NzYsImV4cCI6MjA2NzAyMDc3Nn0.8LZfOWkyVnp-WiEgS0g3YGabV6UCIYY_v6Cd5-6Quxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});